base:
  alternative_bold_font: ./fonts/Roboto-Medium.ttf
  alternative_font: ./fonts/Roboto-Regular.ttf
  bold_font: ./fonts/AlibabaPuHuiTi-2-85-Bold.otf
  bold_font_size: 1
  font: ./fonts/AlibabaPuHuiTi-2-45-Light.otf
  font_size: 1
  quality: 100
  focal_length:
    use_equivalent_focal_length: false
  padding_with_original_ratio:
    enable: false
  shadow:
    enable: false
  white_margin:
    enable: true
    width: 3
layout:
  background_color: '#ffffff'
  elements:
    left_bottom:
      color: '#757575'
      is_bold: false
      name: Model
    left_top:
      color: '#212121'
      is_bold: true
      name: LensModel
    right_bottom:
      color: '#757575'
      is_bold: false
      name: Datetime
      value: Photo by NONE
    right_top:
      color: '#212121'
      is_bold: true
      name: Param
  type: watermark_left_logo
logo:
  enable: true
  position: left
  default: ./logos/fujifilm.png
  directory: ./logos/
